
fuz_quickstart:
    resource: "@FuzQuickStartBundle/Resources/config/routing.yml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

# Hello, world!
geny:
    resource: "@GenyBundle/Controller/"
    type:     annotation
    prefix:   /geny

